import { ArrowRight, BookOpen, ChartNoAxesCombined, Goal, GraduationCap, Landmark, ShieldCheck, TrendingUp, WalletCards } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Brand } from '../components/AuthUI'

const features = [
  [WalletCards, 'Expense Tracking', 'From tracking daily expenses to building a long-term portfolio, we have you covered.'],
  [ChartNoAxesCombined, 'Smart Investments', 'Receive personalized investment suggestions tailored to your risk tolerance and financial goals.'],
  [GraduationCap, 'Financial Education', 'Access bite-sized lessons on budgeting, investing, and building multiple income streams.'],
  [Goal, 'Goal Tracking', 'Set milestones, track progress visually, and get notified when you hit important financial targets.'],
]
const journey = [['01','Sign Up','Create your free account in under 2 minutes and connect your financial profile securely.'],['02','Track & Learn','See where your money goes, discover spending patterns, and access personalized financial tips.'],['03','Invest Wisely','Define savings targets, emergency funds, or investment milestones with smart progress tracking.'],['04','Set Goals','Get AI-powered investment suggestions matched to your risk profile and financial objectives.'],['05','Grow Wealth','Watch your portfolio grow, celebrate milestones, and unlock new financial opportunities.']]
const articles = [['Budgeting','5 Rules for a Bulletproof Monthly Budget','Learn the proven framework that helps thousands save 20% of their income every month without feeling restricted.'],['Investing','Index Funds Vs. Individual Stocks: A Beginner Guide','Understand the key differences, risks, and returns so you can pick the right strategy for your first investment.'],['Quick Cash','7 Side Hustles You Can Start This Weekend','Practical, low-investment ideas to generate extra income using skills you already have.']]

export default function Landing() {
 const navigate = useNavigate()
 return <main className="landing">
  <header className="nav"><button className="brand-button" onClick={() => scrollTo(0,0)} aria-label="GlobalPulse home"><Brand compact /></button><nav aria-label="Account"><button className="nav-login" onClick={() => navigate('/login')}>Log in</button><button className="nav-signup" onClick={() => navigate('/signup')}>Sign up</button></nav></header>
  <section className="hero section"><div className="hero-copy"><h1>Understand Global<br/>Events Before They<br/>Move <em>Indian Markets</em></h1><p>GlobalPulse automatically detects important global events, analyzes their financial ripple effects, connects them with Indian markets, and explains everything in simple language using AI.</p><button className="hero-cta" onClick={() => navigate('/signup')}>Get Start Free <ArrowRight size={18}/></button></div><div className="market-visual" role="img" aria-label="Global market connections"><span className="map-label map-label--one">EUROPE<small>Economic Signal</small></span><span className="map-label map-label--two">INDIA<small>Market Impact</small></span><span className="map-label map-label--three">CHINA<small>Supply & Demand</small></span></div></section>
  <section className="section centered"><span className="eyebrow">FEATURES</span><h2>Everything You Need to Grow <em>Your Wealth</em></h2><p>From tracking daily expenses to building a long-term portfolio, we have you covered.</p><div className="feature-grid">{features.map(([Icon,title,text])=><article className="feature-card" key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="section centered"><span className="eyebrow">YOUR JOURNEY</span><h2>From First Dollar to<br/>Financial <em>Freedom</em></h2><p>Follow a clear path designed to help you build wealth step by step — no finance degree required.</p><div className="journey-list">{journey.map(([n,title,text])=><article key={n}><b>{n}</b><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
  <section className="section centered"><span className="eyebrow">BY THE NUMBERS</span><h2>Trusted by <em>Thousands of Savers</em></h2><div className="stats">{[['2,400+','Active Users'],['$12M+','Tracked Transactions'],['94%','Goal Achievement Rate'],['35%','Avg. Savings Increase']].map(([n,l])=><article key={l}><strong>{n}</strong><span>{l}</span></article>)}</div></section>
  <section className="section centered"><span className="eyebrow">LEARN & EARN</span><h2>Financial Education That Actually <em>Helps</em></h2><div className="articles">{articles.map(([tag,title,text],i)=><article key={title}><span className={`article-tag article-tag--${i}`}>{tag}</span><h3>{title}</h3><p>{text}</p><small>{4+i} min read</small></article>)}</div></section>
  <section className="cta"><Landmark size={28}/><h2>Ready to Take Control of Your Finances?</h2><p>Join thousands of users who are already building smarter financial habits. It takes less than 2 minutes to get started.</p><div><button onClick={()=>navigate('/signup')}>Create Free Account</button><button onClick={()=>navigate('/signup')}>Sign up</button></div></section>
 </main>
}
